

struct ThriftUser {
  1:  required string   lang,
  2:  required bool     verified,
  3:  required i32      followers_count,
  4:  required string   location,
  5:  required string   screen_name,
  6:  required bool     following,
  7:  required i32      friends_count,
  8:  required string   profile_background_color,
  9:  required i32      favourites_count,
  10: required string   description,
  11: required string   notifications,
  12: required string   profile_text_color,
  13: required string   url,
  14: required string   time_zone,
  15: required i32      statuses_count,
  16: required string   profile_link_color,
  17: required bool     geo_enabled,
  18: required string   profile_background_image_url,
  19: required bool     protectedx,
  20: required bool     contributors_enabled,
  21: required string   profile_sidebar_fill_color,
  22: required string   name,
  23: required string   profile_background_tile,
  24: required string   created_at,
  25: required string   profile_image_url,
  26: required i64      id,   
  27: required i32      utc_offset,     
  28: required string   profile_sidebar_border_color,
}

struct ThriftTweet {
  1: required string       text,
  2: required bool         truncated,
  3: required string       geo,
  4: required string       in_reply_to_screen_name,
  5: required bool         favorited,
  6: required string       source,
  7: required string       contributors,
  8: required string       in_reply_to_status_id,
  9: required i64          in_reply_to_user_id,
  10: required i64         id,
  11: required string      id_str,
  12: required string      created_at,
  13: required ThriftUser  user,
}