/* Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package th

import (
  "fmt"
  "github.com/araddon/thrift4go/lib/go/thrift"
)

/**
 * Attributes:
 *  - Lang
 *  - Verified
 *  - FollowersCount
 *  - Location
 *  - ScreenName
 *  - Following
 *  - FriendsCount
 *  - ProfileBackgroundColor
 *  - FavouritesCount
 *  - Description
 *  - Notifications
 *  - ProfileTextColor
 *  - Url
 *  - TimeZone
 *  - StatusesCount
 *  - ProfileLinkColor
 *  - GeoEnabled
 *  - ProfileBackgroundImageUrl
 *  - Protected
 *  - ContributorsEnabled
 *  - ProfileSidebarFillColor
 *  - Name
 *  - ProfileBackgroundTile
 *  - CreatedAt
 *  - ProfileImageUrl
 *  - Id
 *  - UtcOffset
 *  - ProfileSidebarBorderColor
 */
type ThriftUser struct {
  thrift.TStruct
  Lang                      string "lang"                         // 1
  Verified                  bool   "verified"                     // 2
  FollowersCount            int32  "followers_count"              // 3
  Location                  string "location"                     // 4
  ScreenName                string "screen_name"                  // 5
  Following                 bool   "following"                    // 6
  FriendsCount              int32  "friends_count"                // 7
  ProfileBackgroundColor    string "profile_background_color"     // 8
  FavouritesCount           int32  "favourites_count"             // 9
  Description               string "description"                  // 10
  Notifications             string "notifications"                // 11
  ProfileTextColor          string "profile_text_color"           // 12
  Url                       string "url"                          // 13
  TimeZone                  string "time_zone"                    // 14
  StatusesCount             int32  "statuses_count"               // 15
  ProfileLinkColor          string "profile_link_color"           // 16
  GeoEnabled                bool   "geo_enabled"                  // 17
  ProfileBackgroundImageUrl string "profile_background_image_url" // 18
  Protected                 bool   "protected"                    // 19
  ContributorsEnabled       bool   "contributors_enabled"         // 20
  ProfileSidebarFillColor   string "profile_sidebar_fill_color"   // 21
  Name                      string "name"                         // 22
  ProfileBackgroundTile     string "profile_background_tile"      // 23
  CreatedAt                 string "created_at"                   // 24
  ProfileImageUrl           string "profile_image_url"            // 25
  Id                        int64  "id"                           // 26
  UtcOffset                 int32  "utc_offset"                   // 27
  ProfileSidebarBorderColor string "profile_sidebar_border_color" // 28
}

func NewThriftUser() *ThriftUser {
  output := &ThriftUser{
    TStruct: thrift.NewTStruct("ThriftUser", []thrift.TField{
      thrift.NewTField("lang", thrift.STRING, 1),
      thrift.NewTField("verified", thrift.BOOL, 2),
      thrift.NewTField("followers_count", thrift.I32, 3),
      thrift.NewTField("location", thrift.STRING, 4),
      thrift.NewTField("screen_name", thrift.STRING, 5),
      thrift.NewTField("following", thrift.BOOL, 6),
      thrift.NewTField("friends_count", thrift.I32, 7),
      thrift.NewTField("profile_background_color", thrift.STRING, 8),
      thrift.NewTField("favourites_count", thrift.I32, 9),
      thrift.NewTField("description", thrift.STRING, 10),
      thrift.NewTField("notifications", thrift.STRING, 11),
      thrift.NewTField("profile_text_color", thrift.STRING, 12),
      thrift.NewTField("url", thrift.STRING, 13),
      thrift.NewTField("time_zone", thrift.STRING, 14),
      thrift.NewTField("statuses_count", thrift.I32, 15),
      thrift.NewTField("profile_link_color", thrift.STRING, 16),
      thrift.NewTField("geo_enabled", thrift.BOOL, 17),
      thrift.NewTField("profile_background_image_url", thrift.STRING, 18),
      thrift.NewTField("protected", thrift.BOOL, 19),
      thrift.NewTField("contributors_enabled", thrift.BOOL, 20),
      thrift.NewTField("profile_sidebar_fill_color", thrift.STRING, 21),
      thrift.NewTField("name", thrift.STRING, 22),
      thrift.NewTField("profile_background_tile", thrift.STRING, 23),
      thrift.NewTField("created_at", thrift.STRING, 24),
      thrift.NewTField("profile_image_url", thrift.STRING, 25),
      thrift.NewTField("id", thrift.I64, 26),
      thrift.NewTField("utc_offset", thrift.I32, 27),
      thrift.NewTField("profile_sidebar_border_color", thrift.STRING, 28),
    }),
  }
  {
  }
  return output
}

func (p *ThriftUser) Read(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  _, err = iprot.ReadStructBegin()
  if err != nil {
    return thrift.NewTProtocolExceptionReadStruct(p.ThriftName(), err)
  }
  for {
    fieldName, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if fieldId < 0 {
      fieldId = int16(p.FieldIdFromFieldName(fieldName))
    } else if fieldName == "" {
      fieldName = p.FieldNameFromFieldId(int(fieldId))
    }
    if fieldTypeId == thrift.GENERIC {
      fieldTypeId = p.FieldFromFieldId(int(fieldId)).TypeId()
    }
    if err != nil {
      return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
    }
    if fieldTypeId == thrift.STOP {
      break
    }
    if fieldId == 1 || fieldName == "lang" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField1(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField1(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 2 || fieldName == "verified" {
      if fieldTypeId == thrift.BOOL {
        err = p.ReadField2(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField2(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 3 || fieldName == "followers_count" {
      if fieldTypeId == thrift.I32 {
        err = p.ReadField3(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField3(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 4 || fieldName == "location" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField4(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField4(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 5 || fieldName == "screen_name" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField5(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField5(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 6 || fieldName == "following" {
      if fieldTypeId == thrift.BOOL {
        err = p.ReadField6(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField6(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 7 || fieldName == "friends_count" {
      if fieldTypeId == thrift.I32 {
        err = p.ReadField7(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField7(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 8 || fieldName == "profile_background_color" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField8(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField8(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 9 || fieldName == "favourites_count" {
      if fieldTypeId == thrift.I32 {
        err = p.ReadField9(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField9(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 10 || fieldName == "description" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField10(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField10(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 11 || fieldName == "notifications" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField11(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField11(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 12 || fieldName == "profile_text_color" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField12(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField12(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 13 || fieldName == "url" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField13(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField13(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 14 || fieldName == "time_zone" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField14(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField14(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 15 || fieldName == "statuses_count" {
      if fieldTypeId == thrift.I32 {
        err = p.ReadField15(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField15(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 16 || fieldName == "profile_link_color" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField16(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField16(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 17 || fieldName == "geo_enabled" {
      if fieldTypeId == thrift.BOOL {
        err = p.ReadField17(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField17(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 18 || fieldName == "profile_background_image_url" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField18(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField18(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 19 || fieldName == "protected" {
      if fieldTypeId == thrift.BOOL {
        err = p.ReadField19(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField19(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 20 || fieldName == "contributors_enabled" {
      if fieldTypeId == thrift.BOOL {
        err = p.ReadField20(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField20(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 21 || fieldName == "profile_sidebar_fill_color" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField21(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField21(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 22 || fieldName == "name" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField22(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField22(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 23 || fieldName == "profile_background_tile" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField23(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField23(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 24 || fieldName == "created_at" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField24(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField24(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 25 || fieldName == "profile_image_url" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField25(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField25(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 26 || fieldName == "id" {
      if fieldTypeId == thrift.I64 {
        err = p.ReadField26(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField26(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 27 || fieldName == "utc_offset" {
      if fieldTypeId == thrift.I32 {
        err = p.ReadField27(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField27(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 28 || fieldName == "profile_sidebar_border_color" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField28(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField28(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else {
      err = iprot.Skip(fieldTypeId)
      if err != nil {
        return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
      }
    }
    err = iprot.ReadFieldEnd()
    if err != nil {
      return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
    }
  }
  err = iprot.ReadStructEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionReadStruct(p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) ReadField1(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v0, err1 := iprot.ReadString()
  if err1 != nil {
    return thrift.NewTProtocolExceptionReadField(1, "lang", p.ThriftName(), err1)
  }
  p.Lang = v0
  return err
}

func (p *ThriftUser) ReadFieldLang(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField1(iprot)
}

func (p *ThriftUser) ReadField2(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v2, err3 := iprot.ReadBool()
  if err3 != nil {
    return thrift.NewTProtocolExceptionReadField(2, "verified", p.ThriftName(), err3)
  }
  p.Verified = v2
  return err
}

func (p *ThriftUser) ReadFieldVerified(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField2(iprot)
}

func (p *ThriftUser) ReadField3(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v4, err5 := iprot.ReadI32()
  if err5 != nil {
    return thrift.NewTProtocolExceptionReadField(3, "followers_count", p.ThriftName(), err5)
  }
  p.FollowersCount = v4
  return err
}

func (p *ThriftUser) ReadFieldFollowersCount(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField3(iprot)
}

func (p *ThriftUser) ReadField4(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v6, err7 := iprot.ReadString()
  if err7 != nil {
    return thrift.NewTProtocolExceptionReadField(4, "location", p.ThriftName(), err7)
  }
  p.Location = v6
  return err
}

func (p *ThriftUser) ReadFieldLocation(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField4(iprot)
}

func (p *ThriftUser) ReadField5(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v8, err9 := iprot.ReadString()
  if err9 != nil {
    return thrift.NewTProtocolExceptionReadField(5, "screen_name", p.ThriftName(), err9)
  }
  p.ScreenName = v8
  return err
}

func (p *ThriftUser) ReadFieldScreenName(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField5(iprot)
}

func (p *ThriftUser) ReadField6(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v10, err11 := iprot.ReadBool()
  if err11 != nil {
    return thrift.NewTProtocolExceptionReadField(6, "following", p.ThriftName(), err11)
  }
  p.Following = v10
  return err
}

func (p *ThriftUser) ReadFieldFollowing(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField6(iprot)
}

func (p *ThriftUser) ReadField7(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v12, err13 := iprot.ReadI32()
  if err13 != nil {
    return thrift.NewTProtocolExceptionReadField(7, "friends_count", p.ThriftName(), err13)
  }
  p.FriendsCount = v12
  return err
}

func (p *ThriftUser) ReadFieldFriendsCount(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField7(iprot)
}

func (p *ThriftUser) ReadField8(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v14, err15 := iprot.ReadString()
  if err15 != nil {
    return thrift.NewTProtocolExceptionReadField(8, "profile_background_color", p.ThriftName(), err15)
  }
  p.ProfileBackgroundColor = v14
  return err
}

func (p *ThriftUser) ReadFieldProfileBackgroundColor(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField8(iprot)
}

func (p *ThriftUser) ReadField9(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v16, err17 := iprot.ReadI32()
  if err17 != nil {
    return thrift.NewTProtocolExceptionReadField(9, "favourites_count", p.ThriftName(), err17)
  }
  p.FavouritesCount = v16
  return err
}

func (p *ThriftUser) ReadFieldFavouritesCount(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField9(iprot)
}

func (p *ThriftUser) ReadField10(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v18, err19 := iprot.ReadString()
  if err19 != nil {
    return thrift.NewTProtocolExceptionReadField(10, "description", p.ThriftName(), err19)
  }
  p.Description = v18
  return err
}

func (p *ThriftUser) ReadFieldDescription(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField10(iprot)
}

func (p *ThriftUser) ReadField11(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v20, err21 := iprot.ReadString()
  if err21 != nil {
    return thrift.NewTProtocolExceptionReadField(11, "notifications", p.ThriftName(), err21)
  }
  p.Notifications = v20
  return err
}

func (p *ThriftUser) ReadFieldNotifications(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField11(iprot)
}

func (p *ThriftUser) ReadField12(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v22, err23 := iprot.ReadString()
  if err23 != nil {
    return thrift.NewTProtocolExceptionReadField(12, "profile_text_color", p.ThriftName(), err23)
  }
  p.ProfileTextColor = v22
  return err
}

func (p *ThriftUser) ReadFieldProfileTextColor(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField12(iprot)
}

func (p *ThriftUser) ReadField13(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v24, err25 := iprot.ReadString()
  if err25 != nil {
    return thrift.NewTProtocolExceptionReadField(13, "url", p.ThriftName(), err25)
  }
  p.Url = v24
  return err
}

func (p *ThriftUser) ReadFieldUrl(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField13(iprot)
}

func (p *ThriftUser) ReadField14(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v26, err27 := iprot.ReadString()
  if err27 != nil {
    return thrift.NewTProtocolExceptionReadField(14, "time_zone", p.ThriftName(), err27)
  }
  p.TimeZone = v26
  return err
}

func (p *ThriftUser) ReadFieldTimeZone(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField14(iprot)
}

func (p *ThriftUser) ReadField15(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v28, err29 := iprot.ReadI32()
  if err29 != nil {
    return thrift.NewTProtocolExceptionReadField(15, "statuses_count", p.ThriftName(), err29)
  }
  p.StatusesCount = v28
  return err
}

func (p *ThriftUser) ReadFieldStatusesCount(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField15(iprot)
}

func (p *ThriftUser) ReadField16(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v30, err31 := iprot.ReadString()
  if err31 != nil {
    return thrift.NewTProtocolExceptionReadField(16, "profile_link_color", p.ThriftName(), err31)
  }
  p.ProfileLinkColor = v30
  return err
}

func (p *ThriftUser) ReadFieldProfileLinkColor(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField16(iprot)
}

func (p *ThriftUser) ReadField17(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v32, err33 := iprot.ReadBool()
  if err33 != nil {
    return thrift.NewTProtocolExceptionReadField(17, "geo_enabled", p.ThriftName(), err33)
  }
  p.GeoEnabled = v32
  return err
}

func (p *ThriftUser) ReadFieldGeoEnabled(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField17(iprot)
}

func (p *ThriftUser) ReadField18(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v34, err35 := iprot.ReadString()
  if err35 != nil {
    return thrift.NewTProtocolExceptionReadField(18, "profile_background_image_url", p.ThriftName(), err35)
  }
  p.ProfileBackgroundImageUrl = v34
  return err
}

func (p *ThriftUser) ReadFieldProfileBackgroundImageUrl(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField18(iprot)
}

func (p *ThriftUser) ReadField19(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v36, err37 := iprot.ReadBool()
  if err37 != nil {
    return thrift.NewTProtocolExceptionReadField(19, "protected", p.ThriftName(), err37)
  }
  p.Protected = v36
  return err
}

func (p *ThriftUser) ReadFieldprotected(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField19(iprot)
}

func (p *ThriftUser) ReadField20(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v38, err39 := iprot.ReadBool()
  if err39 != nil {
    return thrift.NewTProtocolExceptionReadField(20, "contributors_enabled", p.ThriftName(), err39)
  }
  p.ContributorsEnabled = v38
  return err
}

func (p *ThriftUser) ReadFieldContributorsEnabled(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField20(iprot)
}

func (p *ThriftUser) ReadField21(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v40, err41 := iprot.ReadString()
  if err41 != nil {
    return thrift.NewTProtocolExceptionReadField(21, "profile_sidebar_fill_color", p.ThriftName(), err41)
  }
  p.ProfileSidebarFillColor = v40
  return err
}

func (p *ThriftUser) ReadFieldProfileSidebarFillColor(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField21(iprot)
}

func (p *ThriftUser) ReadField22(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v42, err43 := iprot.ReadString()
  if err43 != nil {
    return thrift.NewTProtocolExceptionReadField(22, "name", p.ThriftName(), err43)
  }
  p.Name = v42
  return err
}

func (p *ThriftUser) ReadFieldName(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField22(iprot)
}

func (p *ThriftUser) ReadField23(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v44, err45 := iprot.ReadString()
  if err45 != nil {
    return thrift.NewTProtocolExceptionReadField(23, "profile_background_tile", p.ThriftName(), err45)
  }
  p.ProfileBackgroundTile = v44
  return err
}

func (p *ThriftUser) ReadFieldProfileBackgroundTile(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField23(iprot)
}

func (p *ThriftUser) ReadField24(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v46, err47 := iprot.ReadString()
  if err47 != nil {
    return thrift.NewTProtocolExceptionReadField(24, "created_at", p.ThriftName(), err47)
  }
  p.CreatedAt = v46
  return err
}

func (p *ThriftUser) ReadFieldCreatedAt(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField24(iprot)
}

func (p *ThriftUser) ReadField25(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v48, err49 := iprot.ReadString()
  if err49 != nil {
    return thrift.NewTProtocolExceptionReadField(25, "profile_image_url", p.ThriftName(), err49)
  }
  p.ProfileImageUrl = v48
  return err
}

func (p *ThriftUser) ReadFieldProfileImageUrl(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField25(iprot)
}

func (p *ThriftUser) ReadField26(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v50, err51 := iprot.ReadI64()
  if err51 != nil {
    return thrift.NewTProtocolExceptionReadField(26, "id", p.ThriftName(), err51)
  }
  p.Id = v50
  return err
}

func (p *ThriftUser) ReadFieldId(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField26(iprot)
}

func (p *ThriftUser) ReadField27(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v52, err53 := iprot.ReadI32()
  if err53 != nil {
    return thrift.NewTProtocolExceptionReadField(27, "utc_offset", p.ThriftName(), err53)
  }
  p.UtcOffset = v52
  return err
}

func (p *ThriftUser) ReadFieldUtcOffset(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField27(iprot)
}

func (p *ThriftUser) ReadField28(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v54, err55 := iprot.ReadString()
  if err55 != nil {
    return thrift.NewTProtocolExceptionReadField(28, "profile_sidebar_border_color", p.ThriftName(), err55)
  }
  p.ProfileSidebarBorderColor = v54
  return err
}

func (p *ThriftUser) ReadFieldProfileSidebarBorderColor(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField28(iprot)
}

func (p *ThriftUser) Write(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteStructBegin("ThriftUser")
  if err != nil {
    return thrift.NewTProtocolExceptionWriteStruct(p.ThriftName(), err)
  }
  err = p.WriteField1(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField2(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField3(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField4(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField5(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField6(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField7(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField8(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField9(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField10(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField11(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField12(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField13(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField14(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField15(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField16(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField17(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField18(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField19(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField20(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField21(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField22(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField23(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField24(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField25(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField26(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField27(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField28(oprot)
  if err != nil {
    return err
  }
  err = oprot.WriteFieldStop()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(-1, "STOP", p.ThriftName(), err)
  }
  err = oprot.WriteStructEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteStruct(p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteField1(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("lang", thrift.STRING, 1)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(1, "lang", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Lang))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(1, "lang", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(1, "lang", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldLang(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField1(oprot)
}

func (p *ThriftUser) WriteField2(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("verified", thrift.BOOL, 2)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(2, "verified", p.ThriftName(), err)
  }
  err = oprot.WriteBool(bool(p.Verified))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(2, "verified", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(2, "verified", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldVerified(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField2(oprot)
}

func (p *ThriftUser) WriteField3(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("followers_count", thrift.I32, 3)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(3, "followers_count", p.ThriftName(), err)
  }
  err = oprot.WriteI32(int32(p.FollowersCount))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(3, "followers_count", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(3, "followers_count", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldFollowersCount(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField3(oprot)
}

func (p *ThriftUser) WriteField4(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("location", thrift.STRING, 4)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(4, "location", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Location))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(4, "location", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(4, "location", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldLocation(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField4(oprot)
}

func (p *ThriftUser) WriteField5(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("screen_name", thrift.STRING, 5)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(5, "screen_name", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.ScreenName))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(5, "screen_name", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(5, "screen_name", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldScreenName(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField5(oprot)
}

func (p *ThriftUser) WriteField6(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("following", thrift.BOOL, 6)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(6, "following", p.ThriftName(), err)
  }
  err = oprot.WriteBool(bool(p.Following))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(6, "following", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(6, "following", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldFollowing(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField6(oprot)
}

func (p *ThriftUser) WriteField7(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("friends_count", thrift.I32, 7)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(7, "friends_count", p.ThriftName(), err)
  }
  err = oprot.WriteI32(int32(p.FriendsCount))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(7, "friends_count", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(7, "friends_count", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldFriendsCount(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField7(oprot)
}

func (p *ThriftUser) WriteField8(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("profile_background_color", thrift.STRING, 8)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(8, "profile_background_color", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.ProfileBackgroundColor))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(8, "profile_background_color", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(8, "profile_background_color", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldProfileBackgroundColor(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField8(oprot)
}

func (p *ThriftUser) WriteField9(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("favourites_count", thrift.I32, 9)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(9, "favourites_count", p.ThriftName(), err)
  }
  err = oprot.WriteI32(int32(p.FavouritesCount))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(9, "favourites_count", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(9, "favourites_count", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldFavouritesCount(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField9(oprot)
}

func (p *ThriftUser) WriteField10(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("description", thrift.STRING, 10)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(10, "description", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Description))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(10, "description", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(10, "description", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldDescription(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField10(oprot)
}

func (p *ThriftUser) WriteField11(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("notifications", thrift.STRING, 11)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(11, "notifications", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Notifications))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(11, "notifications", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(11, "notifications", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldNotifications(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField11(oprot)
}

func (p *ThriftUser) WriteField12(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("profile_text_color", thrift.STRING, 12)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(12, "profile_text_color", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.ProfileTextColor))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(12, "profile_text_color", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(12, "profile_text_color", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldProfileTextColor(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField12(oprot)
}

func (p *ThriftUser) WriteField13(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("url", thrift.STRING, 13)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(13, "url", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Url))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(13, "url", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(13, "url", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldUrl(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField13(oprot)
}

func (p *ThriftUser) WriteField14(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("time_zone", thrift.STRING, 14)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(14, "time_zone", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.TimeZone))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(14, "time_zone", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(14, "time_zone", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldTimeZone(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField14(oprot)
}

func (p *ThriftUser) WriteField15(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("statuses_count", thrift.I32, 15)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(15, "statuses_count", p.ThriftName(), err)
  }
  err = oprot.WriteI32(int32(p.StatusesCount))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(15, "statuses_count", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(15, "statuses_count", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldStatusesCount(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField15(oprot)
}

func (p *ThriftUser) WriteField16(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("profile_link_color", thrift.STRING, 16)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(16, "profile_link_color", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.ProfileLinkColor))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(16, "profile_link_color", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(16, "profile_link_color", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldProfileLinkColor(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField16(oprot)
}

func (p *ThriftUser) WriteField17(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("geo_enabled", thrift.BOOL, 17)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(17, "geo_enabled", p.ThriftName(), err)
  }
  err = oprot.WriteBool(bool(p.GeoEnabled))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(17, "geo_enabled", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(17, "geo_enabled", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldGeoEnabled(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField17(oprot)
}

func (p *ThriftUser) WriteField18(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("profile_background_image_url", thrift.STRING, 18)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(18, "profile_background_image_url", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.ProfileBackgroundImageUrl))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(18, "profile_background_image_url", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(18, "profile_background_image_url", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldProfileBackgroundImageUrl(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField18(oprot)
}

func (p *ThriftUser) WriteField19(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("protected", thrift.BOOL, 19)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(19, "protected", p.ThriftName(), err)
  }
  err = oprot.WriteBool(bool(p.Protected))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(19, "protected", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(19, "protected", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldprotected(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField19(oprot)
}

func (p *ThriftUser) WriteField20(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("contributors_enabled", thrift.BOOL, 20)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(20, "contributors_enabled", p.ThriftName(), err)
  }
  err = oprot.WriteBool(bool(p.ContributorsEnabled))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(20, "contributors_enabled", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(20, "contributors_enabled", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldContributorsEnabled(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField20(oprot)
}

func (p *ThriftUser) WriteField21(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("profile_sidebar_fill_color", thrift.STRING, 21)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(21, "profile_sidebar_fill_color", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.ProfileSidebarFillColor))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(21, "profile_sidebar_fill_color", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(21, "profile_sidebar_fill_color", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldProfileSidebarFillColor(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField21(oprot)
}

func (p *ThriftUser) WriteField22(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("name", thrift.STRING, 22)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(22, "name", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Name))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(22, "name", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(22, "name", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldName(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField22(oprot)
}

func (p *ThriftUser) WriteField23(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("profile_background_tile", thrift.STRING, 23)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(23, "profile_background_tile", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.ProfileBackgroundTile))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(23, "profile_background_tile", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(23, "profile_background_tile", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldProfileBackgroundTile(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField23(oprot)
}

func (p *ThriftUser) WriteField24(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("created_at", thrift.STRING, 24)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(24, "created_at", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.CreatedAt))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(24, "created_at", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(24, "created_at", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldCreatedAt(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField24(oprot)
}

func (p *ThriftUser) WriteField25(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("profile_image_url", thrift.STRING, 25)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(25, "profile_image_url", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.ProfileImageUrl))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(25, "profile_image_url", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(25, "profile_image_url", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldProfileImageUrl(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField25(oprot)
}

func (p *ThriftUser) WriteField26(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("id", thrift.I64, 26)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(26, "id", p.ThriftName(), err)
  }
  err = oprot.WriteI64(int64(p.Id))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(26, "id", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(26, "id", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldId(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField26(oprot)
}

func (p *ThriftUser) WriteField27(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("utc_offset", thrift.I32, 27)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(27, "utc_offset", p.ThriftName(), err)
  }
  err = oprot.WriteI32(int32(p.UtcOffset))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(27, "utc_offset", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(27, "utc_offset", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldUtcOffset(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField27(oprot)
}

func (p *ThriftUser) WriteField28(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("profile_sidebar_border_color", thrift.STRING, 28)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(28, "profile_sidebar_border_color", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.ProfileSidebarBorderColor))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(28, "profile_sidebar_border_color", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(28, "profile_sidebar_border_color", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftUser) WriteFieldProfileSidebarBorderColor(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField28(oprot)
}

func (p *ThriftUser) TStructName() string {
  return "ThriftUser"
}

func (p *ThriftUser) ThriftName() string {
  return "ThriftUser"
}

func (p *ThriftUser) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ThriftUser(%+v)", *p)
}

func (p *ThriftUser) CompareTo(other interface{}) (int, bool) {
  if other == nil {
    return 1, true
  }
  data, ok := other.(*ThriftUser)
  if !ok {
    return 0, false
  }
  if p.Lang != data.Lang {
    if p.Lang < data.Lang {
      return -1, true
    }
    return 1, true
  }
  if cmp := thrift.CompareBool(p.Verified, data.Verified); cmp != 0 {
    return cmp, true
  }
  if p.FollowersCount != data.FollowersCount {
    if p.FollowersCount < data.FollowersCount {
      return -1, true
    }
    return 1, true
  }
  if p.Location != data.Location {
    if p.Location < data.Location {
      return -1, true
    }
    return 1, true
  }
  if p.ScreenName != data.ScreenName {
    if p.ScreenName < data.ScreenName {
      return -1, true
    }
    return 1, true
  }
  if cmp := thrift.CompareBool(p.Following, data.Following); cmp != 0 {
    return cmp, true
  }
  if p.FriendsCount != data.FriendsCount {
    if p.FriendsCount < data.FriendsCount {
      return -1, true
    }
    return 1, true
  }
  if p.ProfileBackgroundColor != data.ProfileBackgroundColor {
    if p.ProfileBackgroundColor < data.ProfileBackgroundColor {
      return -1, true
    }
    return 1, true
  }
  if p.FavouritesCount != data.FavouritesCount {
    if p.FavouritesCount < data.FavouritesCount {
      return -1, true
    }
    return 1, true
  }
  if p.Description != data.Description {
    if p.Description < data.Description {
      return -1, true
    }
    return 1, true
  }
  if p.Notifications != data.Notifications {
    if p.Notifications < data.Notifications {
      return -1, true
    }
    return 1, true
  }
  if p.ProfileTextColor != data.ProfileTextColor {
    if p.ProfileTextColor < data.ProfileTextColor {
      return -1, true
    }
    return 1, true
  }
  if p.Url != data.Url {
    if p.Url < data.Url {
      return -1, true
    }
    return 1, true
  }
  if p.TimeZone != data.TimeZone {
    if p.TimeZone < data.TimeZone {
      return -1, true
    }
    return 1, true
  }
  if p.StatusesCount != data.StatusesCount {
    if p.StatusesCount < data.StatusesCount {
      return -1, true
    }
    return 1, true
  }
  if p.ProfileLinkColor != data.ProfileLinkColor {
    if p.ProfileLinkColor < data.ProfileLinkColor {
      return -1, true
    }
    return 1, true
  }
  if cmp := thrift.CompareBool(p.GeoEnabled, data.GeoEnabled); cmp != 0 {
    return cmp, true
  }
  if p.ProfileBackgroundImageUrl != data.ProfileBackgroundImageUrl {
    if p.ProfileBackgroundImageUrl < data.ProfileBackgroundImageUrl {
      return -1, true
    }
    return 1, true
  }
  if cmp := thrift.CompareBool(p.Protected, data.Protected); cmp != 0 {
    return cmp, true
  }
  if cmp := thrift.CompareBool(p.ContributorsEnabled, data.ContributorsEnabled); cmp != 0 {
    return cmp, true
  }
  if p.ProfileSidebarFillColor != data.ProfileSidebarFillColor {
    if p.ProfileSidebarFillColor < data.ProfileSidebarFillColor {
      return -1, true
    }
    return 1, true
  }
  if p.Name != data.Name {
    if p.Name < data.Name {
      return -1, true
    }
    return 1, true
  }
  if p.ProfileBackgroundTile != data.ProfileBackgroundTile {
    if p.ProfileBackgroundTile < data.ProfileBackgroundTile {
      return -1, true
    }
    return 1, true
  }
  if p.CreatedAt != data.CreatedAt {
    if p.CreatedAt < data.CreatedAt {
      return -1, true
    }
    return 1, true
  }
  if p.ProfileImageUrl != data.ProfileImageUrl {
    if p.ProfileImageUrl < data.ProfileImageUrl {
      return -1, true
    }
    return 1, true
  }
  if p.Id != data.Id {
    if p.Id < data.Id {
      return -1, true
    }
    return 1, true
  }
  if p.UtcOffset != data.UtcOffset {
    if p.UtcOffset < data.UtcOffset {
      return -1, true
    }
    return 1, true
  }
  if p.ProfileSidebarBorderColor != data.ProfileSidebarBorderColor {
    if p.ProfileSidebarBorderColor < data.ProfileSidebarBorderColor {
      return -1, true
    }
    return 1, true
  }
  return 0, true
}

func (p *ThriftUser) AttributeByFieldId(id int) interface{} {
  switch id {
  default:
    return nil
  case 1:
    return p.Lang
  case 2:
    return p.Verified
  case 3:
    return p.FollowersCount
  case 4:
    return p.Location
  case 5:
    return p.ScreenName
  case 6:
    return p.Following
  case 7:
    return p.FriendsCount
  case 8:
    return p.ProfileBackgroundColor
  case 9:
    return p.FavouritesCount
  case 10:
    return p.Description
  case 11:
    return p.Notifications
  case 12:
    return p.ProfileTextColor
  case 13:
    return p.Url
  case 14:
    return p.TimeZone
  case 15:
    return p.StatusesCount
  case 16:
    return p.ProfileLinkColor
  case 17:
    return p.GeoEnabled
  case 18:
    return p.ProfileBackgroundImageUrl
  case 19:
    return p.Protected
  case 20:
    return p.ContributorsEnabled
  case 21:
    return p.ProfileSidebarFillColor
  case 22:
    return p.Name
  case 23:
    return p.ProfileBackgroundTile
  case 24:
    return p.CreatedAt
  case 25:
    return p.ProfileImageUrl
  case 26:
    return p.Id
  case 27:
    return p.UtcOffset
  case 28:
    return p.ProfileSidebarBorderColor
  }
  return nil
}

func (p *ThriftUser) TStructFields() thrift.TFieldContainer {
  return thrift.NewTFieldContainer([]thrift.TField{
    thrift.NewTField("lang", thrift.STRING, 1),
    thrift.NewTField("verified", thrift.BOOL, 2),
    thrift.NewTField("followers_count", thrift.I32, 3),
    thrift.NewTField("location", thrift.STRING, 4),
    thrift.NewTField("screen_name", thrift.STRING, 5),
    thrift.NewTField("following", thrift.BOOL, 6),
    thrift.NewTField("friends_count", thrift.I32, 7),
    thrift.NewTField("profile_background_color", thrift.STRING, 8),
    thrift.NewTField("favourites_count", thrift.I32, 9),
    thrift.NewTField("description", thrift.STRING, 10),
    thrift.NewTField("notifications", thrift.STRING, 11),
    thrift.NewTField("profile_text_color", thrift.STRING, 12),
    thrift.NewTField("url", thrift.STRING, 13),
    thrift.NewTField("time_zone", thrift.STRING, 14),
    thrift.NewTField("statuses_count", thrift.I32, 15),
    thrift.NewTField("profile_link_color", thrift.STRING, 16),
    thrift.NewTField("geo_enabled", thrift.BOOL, 17),
    thrift.NewTField("profile_background_image_url", thrift.STRING, 18),
    thrift.NewTField("protected", thrift.BOOL, 19),
    thrift.NewTField("contributors_enabled", thrift.BOOL, 20),
    thrift.NewTField("profile_sidebar_fill_color", thrift.STRING, 21),
    thrift.NewTField("name", thrift.STRING, 22),
    thrift.NewTField("profile_background_tile", thrift.STRING, 23),
    thrift.NewTField("created_at", thrift.STRING, 24),
    thrift.NewTField("profile_image_url", thrift.STRING, 25),
    thrift.NewTField("id", thrift.I64, 26),
    thrift.NewTField("utc_offset", thrift.I32, 27),
    thrift.NewTField("profile_sidebar_border_color", thrift.STRING, 28),
  })
}

/**
 * Attributes:
 *  - Text
 *  - Truncated
 *  - Geo
 *  - InReplyToScreenName
 *  - Favorited
 *  - Source
 *  - Contributors
 *  - InReplyToStatusId
 *  - InReplyToUserId
 *  - Id
 *  - IdStr
 *  - CreatedAt
 *  - User
 */
type ThriftTweet struct {
  thrift.TStruct
  Text                string      "text"                    // 1
  Truncated           bool        "truncated"               // 2
  Geo                 string      "geo"                     // 3
  InReplyToScreenName string      "in_reply_to_screen_name" // 4
  Favorited           bool        "favorited"               // 5
  Source              string      "source"                  // 6
  Contributors        string      "contributors"            // 7
  InReplyToStatusId   string      "in_reply_to_status_id"   // 8
  InReplyToUserId     int64       "in_reply_to_user_id"     // 9
  Id                  int64       "id"                      // 10
  IdStr               string      "id_str"                  // 11
  CreatedAt           string      "created_at"              // 12
  User                *ThriftUser "user"                    // 13
}

func NewThriftTweet() *ThriftTweet {
  output := &ThriftTweet{
    TStruct: thrift.NewTStruct("ThriftTweet", []thrift.TField{
      thrift.NewTField("text", thrift.STRING, 1),
      thrift.NewTField("truncated", thrift.BOOL, 2),
      thrift.NewTField("geo", thrift.STRING, 3),
      thrift.NewTField("in_reply_to_screen_name", thrift.STRING, 4),
      thrift.NewTField("favorited", thrift.BOOL, 5),
      thrift.NewTField("source", thrift.STRING, 6),
      thrift.NewTField("contributors", thrift.STRING, 7),
      thrift.NewTField("in_reply_to_status_id", thrift.STRING, 8),
      thrift.NewTField("in_reply_to_user_id", thrift.I64, 9),
      thrift.NewTField("id", thrift.I64, 10),
      thrift.NewTField("id_str", thrift.STRING, 11),
      thrift.NewTField("created_at", thrift.STRING, 12),
      thrift.NewTField("user", thrift.STRUCT, 13),
    }),
  }
  {
  }
  return output
}

func (p *ThriftTweet) Read(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  _, err = iprot.ReadStructBegin()
  if err != nil {
    return thrift.NewTProtocolExceptionReadStruct(p.ThriftName(), err)
  }
  for {
    fieldName, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if fieldId < 0 {
      fieldId = int16(p.FieldIdFromFieldName(fieldName))
    } else if fieldName == "" {
      fieldName = p.FieldNameFromFieldId(int(fieldId))
    }
    if fieldTypeId == thrift.GENERIC {
      fieldTypeId = p.FieldFromFieldId(int(fieldId)).TypeId()
    }
    if err != nil {
      return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
    }
    if fieldTypeId == thrift.STOP {
      break
    }
    if fieldId == 1 || fieldName == "text" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField1(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField1(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 2 || fieldName == "truncated" {
      if fieldTypeId == thrift.BOOL {
        err = p.ReadField2(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField2(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 3 || fieldName == "geo" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField3(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField3(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 4 || fieldName == "in_reply_to_screen_name" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField4(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField4(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 5 || fieldName == "favorited" {
      if fieldTypeId == thrift.BOOL {
        err = p.ReadField5(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField5(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 6 || fieldName == "source" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField6(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField6(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 7 || fieldName == "contributors" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField7(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField7(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 8 || fieldName == "in_reply_to_status_id" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField8(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField8(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 9 || fieldName == "in_reply_to_user_id" {
      if fieldTypeId == thrift.I64 {
        err = p.ReadField9(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField9(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 10 || fieldName == "id" {
      if fieldTypeId == thrift.I64 {
        err = p.ReadField10(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField10(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 11 || fieldName == "id_str" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField11(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField11(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 12 || fieldName == "created_at" {
      if fieldTypeId == thrift.STRING {
        err = p.ReadField12(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField12(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else if fieldId == 13 || fieldName == "user" {
      if fieldTypeId == thrift.STRUCT {
        err = p.ReadField13(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else if fieldTypeId == thrift.VOID {
        err = iprot.Skip(fieldTypeId)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      } else {
        err = p.ReadField13(iprot)
        if err != nil {
          return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
        }
      }
    } else {
      err = iprot.Skip(fieldTypeId)
      if err != nil {
        return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
      }
    }
    err = iprot.ReadFieldEnd()
    if err != nil {
      return thrift.NewTProtocolExceptionReadField(int(fieldId), fieldName, p.ThriftName(), err)
    }
  }
  err = iprot.ReadStructEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionReadStruct(p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) ReadField1(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v56, err57 := iprot.ReadString()
  if err57 != nil {
    return thrift.NewTProtocolExceptionReadField(1, "text", p.ThriftName(), err57)
  }
  p.Text = v56
  return err
}

func (p *ThriftTweet) ReadFieldText(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField1(iprot)
}

func (p *ThriftTweet) ReadField2(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v58, err59 := iprot.ReadBool()
  if err59 != nil {
    return thrift.NewTProtocolExceptionReadField(2, "truncated", p.ThriftName(), err59)
  }
  p.Truncated = v58
  return err
}

func (p *ThriftTweet) ReadFieldTruncated(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField2(iprot)
}

func (p *ThriftTweet) ReadField3(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v60, err61 := iprot.ReadString()
  if err61 != nil {
    return thrift.NewTProtocolExceptionReadField(3, "geo", p.ThriftName(), err61)
  }
  p.Geo = v60
  return err
}

func (p *ThriftTweet) ReadFieldGeo(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField3(iprot)
}

func (p *ThriftTweet) ReadField4(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v62, err63 := iprot.ReadString()
  if err63 != nil {
    return thrift.NewTProtocolExceptionReadField(4, "in_reply_to_screen_name", p.ThriftName(), err63)
  }
  p.InReplyToScreenName = v62
  return err
}

func (p *ThriftTweet) ReadFieldInReplyToScreenName(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField4(iprot)
}

func (p *ThriftTweet) ReadField5(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v64, err65 := iprot.ReadBool()
  if err65 != nil {
    return thrift.NewTProtocolExceptionReadField(5, "favorited", p.ThriftName(), err65)
  }
  p.Favorited = v64
  return err
}

func (p *ThriftTweet) ReadFieldFavorited(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField5(iprot)
}

func (p *ThriftTweet) ReadField6(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v66, err67 := iprot.ReadString()
  if err67 != nil {
    return thrift.NewTProtocolExceptionReadField(6, "source", p.ThriftName(), err67)
  }
  p.Source = v66
  return err
}

func (p *ThriftTweet) ReadFieldSource(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField6(iprot)
}

func (p *ThriftTweet) ReadField7(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v68, err69 := iprot.ReadString()
  if err69 != nil {
    return thrift.NewTProtocolExceptionReadField(7, "contributors", p.ThriftName(), err69)
  }
  p.Contributors = v68
  return err
}

func (p *ThriftTweet) ReadFieldContributors(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField7(iprot)
}

func (p *ThriftTweet) ReadField8(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v70, err71 := iprot.ReadString()
  if err71 != nil {
    return thrift.NewTProtocolExceptionReadField(8, "in_reply_to_status_id", p.ThriftName(), err71)
  }
  p.InReplyToStatusId = v70
  return err
}

func (p *ThriftTweet) ReadFieldInReplyToStatusId(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField8(iprot)
}

func (p *ThriftTweet) ReadField9(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v72, err73 := iprot.ReadI64()
  if err73 != nil {
    return thrift.NewTProtocolExceptionReadField(9, "in_reply_to_user_id", p.ThriftName(), err73)
  }
  p.InReplyToUserId = v72
  return err
}

func (p *ThriftTweet) ReadFieldInReplyToUserId(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField9(iprot)
}

func (p *ThriftTweet) ReadField10(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v74, err75 := iprot.ReadI64()
  if err75 != nil {
    return thrift.NewTProtocolExceptionReadField(10, "id", p.ThriftName(), err75)
  }
  p.Id = v74
  return err
}

func (p *ThriftTweet) ReadFieldId(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField10(iprot)
}

func (p *ThriftTweet) ReadField11(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v76, err77 := iprot.ReadString()
  if err77 != nil {
    return thrift.NewTProtocolExceptionReadField(11, "id_str", p.ThriftName(), err77)
  }
  p.IdStr = v76
  return err
}

func (p *ThriftTweet) ReadFieldIdStr(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField11(iprot)
}

func (p *ThriftTweet) ReadField12(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  v78, err79 := iprot.ReadString()
  if err79 != nil {
    return thrift.NewTProtocolExceptionReadField(12, "created_at", p.ThriftName(), err79)
  }
  p.CreatedAt = v78
  return err
}

func (p *ThriftTweet) ReadFieldCreatedAt(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField12(iprot)
}

func (p *ThriftTweet) ReadField13(iprot thrift.TProtocol) (err thrift.TProtocolException) {
  p.User = NewThriftUser()
  err82 := p.User.Read(iprot)
  if err82 != nil {
    return thrift.NewTProtocolExceptionReadStruct("p.UserThriftUser", err82)
  }
  return err
}

func (p *ThriftTweet) ReadFieldUser(iprot thrift.TProtocol) thrift.TProtocolException {
  return p.ReadField13(iprot)
}

func (p *ThriftTweet) Write(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteStructBegin("ThriftTweet")
  if err != nil {
    return thrift.NewTProtocolExceptionWriteStruct(p.ThriftName(), err)
  }
  err = p.WriteField1(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField2(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField3(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField4(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField5(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField6(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField7(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField8(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField9(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField10(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField11(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField12(oprot)
  if err != nil {
    return err
  }
  err = p.WriteField13(oprot)
  if err != nil {
    return err
  }
  err = oprot.WriteFieldStop()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(-1, "STOP", p.ThriftName(), err)
  }
  err = oprot.WriteStructEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteStruct(p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteField1(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("text", thrift.STRING, 1)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(1, "text", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Text))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(1, "text", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(1, "text", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldText(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField1(oprot)
}

func (p *ThriftTweet) WriteField2(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("truncated", thrift.BOOL, 2)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(2, "truncated", p.ThriftName(), err)
  }
  err = oprot.WriteBool(bool(p.Truncated))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(2, "truncated", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(2, "truncated", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldTruncated(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField2(oprot)
}

func (p *ThriftTweet) WriteField3(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("geo", thrift.STRING, 3)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(3, "geo", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Geo))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(3, "geo", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(3, "geo", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldGeo(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField3(oprot)
}

func (p *ThriftTweet) WriteField4(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("in_reply_to_screen_name", thrift.STRING, 4)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(4, "in_reply_to_screen_name", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.InReplyToScreenName))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(4, "in_reply_to_screen_name", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(4, "in_reply_to_screen_name", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldInReplyToScreenName(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField4(oprot)
}

func (p *ThriftTweet) WriteField5(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("favorited", thrift.BOOL, 5)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(5, "favorited", p.ThriftName(), err)
  }
  err = oprot.WriteBool(bool(p.Favorited))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(5, "favorited", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(5, "favorited", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldFavorited(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField5(oprot)
}

func (p *ThriftTweet) WriteField6(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("source", thrift.STRING, 6)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(6, "source", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Source))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(6, "source", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(6, "source", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldSource(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField6(oprot)
}

func (p *ThriftTweet) WriteField7(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("contributors", thrift.STRING, 7)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(7, "contributors", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.Contributors))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(7, "contributors", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(7, "contributors", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldContributors(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField7(oprot)
}

func (p *ThriftTweet) WriteField8(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("in_reply_to_status_id", thrift.STRING, 8)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(8, "in_reply_to_status_id", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.InReplyToStatusId))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(8, "in_reply_to_status_id", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(8, "in_reply_to_status_id", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldInReplyToStatusId(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField8(oprot)
}

func (p *ThriftTweet) WriteField9(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("in_reply_to_user_id", thrift.I64, 9)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(9, "in_reply_to_user_id", p.ThriftName(), err)
  }
  err = oprot.WriteI64(int64(p.InReplyToUserId))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(9, "in_reply_to_user_id", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(9, "in_reply_to_user_id", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldInReplyToUserId(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField9(oprot)
}

func (p *ThriftTweet) WriteField10(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("id", thrift.I64, 10)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(10, "id", p.ThriftName(), err)
  }
  err = oprot.WriteI64(int64(p.Id))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(10, "id", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(10, "id", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldId(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField10(oprot)
}

func (p *ThriftTweet) WriteField11(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("id_str", thrift.STRING, 11)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(11, "id_str", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.IdStr))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(11, "id_str", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(11, "id_str", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldIdStr(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField11(oprot)
}

func (p *ThriftTweet) WriteField12(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  err = oprot.WriteFieldBegin("created_at", thrift.STRING, 12)
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(12, "created_at", p.ThriftName(), err)
  }
  err = oprot.WriteString(string(p.CreatedAt))
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(12, "created_at", p.ThriftName(), err)
  }
  err = oprot.WriteFieldEnd()
  if err != nil {
    return thrift.NewTProtocolExceptionWriteField(12, "created_at", p.ThriftName(), err)
  }
  return err
}

func (p *ThriftTweet) WriteFieldCreatedAt(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField12(oprot)
}

func (p *ThriftTweet) WriteField13(oprot thrift.TProtocol) (err thrift.TProtocolException) {
  if p.User != nil {
    err = oprot.WriteFieldBegin("user", thrift.STRUCT, 13)
    if err != nil {
      return thrift.NewTProtocolExceptionWriteField(13, "user", p.ThriftName(), err)
    }
    err = p.User.Write(oprot)
    if err != nil {
      return thrift.NewTProtocolExceptionWriteStruct("ThriftUser", err)
    }
    err = oprot.WriteFieldEnd()
    if err != nil {
      return thrift.NewTProtocolExceptionWriteField(13, "user", p.ThriftName(), err)
    }
  }
  return err
}

func (p *ThriftTweet) WriteFieldUser(oprot thrift.TProtocol) thrift.TProtocolException {
  return p.WriteField13(oprot)
}

func (p *ThriftTweet) TStructName() string {
  return "ThriftTweet"
}

func (p *ThriftTweet) ThriftName() string {
  return "ThriftTweet"
}

func (p *ThriftTweet) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ThriftTweet(%+v)", *p)
}

func (p *ThriftTweet) CompareTo(other interface{}) (int, bool) {
  if other == nil {
    return 1, true
  }
  data, ok := other.(*ThriftTweet)
  if !ok {
    return 0, false
  }
  if p.Text != data.Text {
    if p.Text < data.Text {
      return -1, true
    }
    return 1, true
  }
  if cmp := thrift.CompareBool(p.Truncated, data.Truncated); cmp != 0 {
    return cmp, true
  }
  if p.Geo != data.Geo {
    if p.Geo < data.Geo {
      return -1, true
    }
    return 1, true
  }
  if p.InReplyToScreenName != data.InReplyToScreenName {
    if p.InReplyToScreenName < data.InReplyToScreenName {
      return -1, true
    }
    return 1, true
  }
  if cmp := thrift.CompareBool(p.Favorited, data.Favorited); cmp != 0 {
    return cmp, true
  }
  if p.Source != data.Source {
    if p.Source < data.Source {
      return -1, true
    }
    return 1, true
  }
  if p.Contributors != data.Contributors {
    if p.Contributors < data.Contributors {
      return -1, true
    }
    return 1, true
  }
  if p.InReplyToStatusId != data.InReplyToStatusId {
    if p.InReplyToStatusId < data.InReplyToStatusId {
      return -1, true
    }
    return 1, true
  }
  if p.InReplyToUserId != data.InReplyToUserId {
    if p.InReplyToUserId < data.InReplyToUserId {
      return -1, true
    }
    return 1, true
  }
  if p.Id != data.Id {
    if p.Id < data.Id {
      return -1, true
    }
    return 1, true
  }
  if p.IdStr != data.IdStr {
    if p.IdStr < data.IdStr {
      return -1, true
    }
    return 1, true
  }
  if p.CreatedAt != data.CreatedAt {
    if p.CreatedAt < data.CreatedAt {
      return -1, true
    }
    return 1, true
  }
  if cmp, ok := p.User.CompareTo(data.User); !ok || cmp != 0 {
    return cmp, ok
  }
  return 0, true
}

func (p *ThriftTweet) AttributeByFieldId(id int) interface{} {
  switch id {
  default:
    return nil
  case 1:
    return p.Text
  case 2:
    return p.Truncated
  case 3:
    return p.Geo
  case 4:
    return p.InReplyToScreenName
  case 5:
    return p.Favorited
  case 6:
    return p.Source
  case 7:
    return p.Contributors
  case 8:
    return p.InReplyToStatusId
  case 9:
    return p.InReplyToUserId
  case 10:
    return p.Id
  case 11:
    return p.IdStr
  case 12:
    return p.CreatedAt
  case 13:
    return p.User
  }
  return nil
}

func (p *ThriftTweet) TStructFields() thrift.TFieldContainer {
  return thrift.NewTFieldContainer([]thrift.TField{
    thrift.NewTField("text", thrift.STRING, 1),
    thrift.NewTField("truncated", thrift.BOOL, 2),
    thrift.NewTField("geo", thrift.STRING, 3),
    thrift.NewTField("in_reply_to_screen_name", thrift.STRING, 4),
    thrift.NewTField("favorited", thrift.BOOL, 5),
    thrift.NewTField("source", thrift.STRING, 6),
    thrift.NewTField("contributors", thrift.STRING, 7),
    thrift.NewTField("in_reply_to_status_id", thrift.STRING, 8),
    thrift.NewTField("in_reply_to_user_id", thrift.I64, 9),
    thrift.NewTField("id", thrift.I64, 10),
    thrift.NewTField("id_str", thrift.STRING, 11),
    thrift.NewTField("created_at", thrift.STRING, 12),
    thrift.NewTField("user", thrift.STRUCT, 13),
  })
}

func init() {
}
