// Code generated by protoc-gen-go from "twtypes.proto"
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Tweet struct {
	Text                *string         `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Truncated           *bool           `protobuf:"varint,2,opt,name=truncated" json:"truncated,omitempty"`
	Geo                 *string         `protobuf:"bytes,3,opt,name=geo" json:"geo,omitempty"`
	InReplyToScreenName *string         `protobuf:"bytes,4,opt,name=in_reply_to_screen_name" json:"in_reply_to_screen_name,omitempty"`
	Favorited           *bool           `protobuf:"varint,5,opt,name=favorited" json:"favorited,omitempty"`
	Source              *string         `protobuf:"bytes,6,opt,name=source" json:"source,omitempty"`
	Contributors        *string         `protobuf:"bytes,7,opt,name=contributors" json:"contributors,omitempty"`
	InReplyToStatusId   *string         `protobuf:"bytes,8,opt,name=in_reply_to_status_id" json:"in_reply_to_status_id,omitempty"`
	InReplyToUserId     *int64          `protobuf:"varint,9,opt,name=in_reply_to_user_id" json:"in_reply_to_user_id,omitempty"`
	Id                  *int64          `protobuf:"varint,10,opt,name=id" json:"id,omitempty"`
	IdStr               *string         `protobuf:"bytes,11,opt,name=id_str" json:"id_str,omitempty"`
	CreatedAt           *string         `protobuf:"bytes,12,opt,name=created_at" json:"created_at,omitempty"`
	User                *User           `protobuf:"bytes,13,opt,name=user" json:"user,omitempty"`
	Header              []*Tweet_Header `protobuf:"bytes,14,rep,name=header" json:"header,omitempty"`
	XXX_unrecognized    []byte          `json:"-"`
}

func (this *Tweet) Reset()         { *this = Tweet{} }
func (this *Tweet) String() string { return proto.CompactTextString(this) }
func (*Tweet) ProtoMessage()       {}

func (this *Tweet) GetText() string {
	if this != nil && this.Text != nil {
		return *this.Text
	}
	return ""
}

func (this *Tweet) GetTruncated() bool {
	if this != nil && this.Truncated != nil {
		return *this.Truncated
	}
	return false
}

func (this *Tweet) GetGeo() string {
	if this != nil && this.Geo != nil {
		return *this.Geo
	}
	return ""
}

func (this *Tweet) GetInReplyToScreenName() string {
	if this != nil && this.InReplyToScreenName != nil {
		return *this.InReplyToScreenName
	}
	return ""
}

func (this *Tweet) GetFavorited() bool {
	if this != nil && this.Favorited != nil {
		return *this.Favorited
	}
	return false
}

func (this *Tweet) GetSource() string {
	if this != nil && this.Source != nil {
		return *this.Source
	}
	return ""
}

func (this *Tweet) GetContributors() string {
	if this != nil && this.Contributors != nil {
		return *this.Contributors
	}
	return ""
}

func (this *Tweet) GetInReplyToStatusId() string {
	if this != nil && this.InReplyToStatusId != nil {
		return *this.InReplyToStatusId
	}
	return ""
}

func (this *Tweet) GetInReplyToUserId() int64 {
	if this != nil && this.InReplyToUserId != nil {
		return *this.InReplyToUserId
	}
	return 0
}

func (this *Tweet) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Tweet) GetIdStr() string {
	if this != nil && this.IdStr != nil {
		return *this.IdStr
	}
	return ""
}

func (this *Tweet) GetCreatedAt() string {
	if this != nil && this.CreatedAt != nil {
		return *this.CreatedAt
	}
	return ""
}

func (this *Tweet) GetUser() *User {
	if this != nil {
		return this.User
	}
	return nil
}

type Tweet_Header struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Tweet_Header) Reset()         { *this = Tweet_Header{} }
func (this *Tweet_Header) String() string { return proto.CompactTextString(this) }
func (*Tweet_Header) ProtoMessage()       {}

func (this *Tweet_Header) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Tweet_Header) GetValue() string {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return ""
}

type User struct {
	Lang                      *string `protobuf:"bytes,1,opt,name=lang" json:"lang,omitempty"`
	Verified                  *bool   `protobuf:"varint,2,opt,name=verified" json:"verified,omitempty"`
	FollowersCount            *int32  `protobuf:"varint,3,opt,name=followers_count" json:"followers_count,omitempty"`
	Location                  *string `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	ScreenName                *string `protobuf:"bytes,5,opt,name=screen_name" json:"screen_name,omitempty"`
	Following                 *bool   `protobuf:"varint,6,opt,name=following" json:"following,omitempty"`
	FriendsCount              *int32  `protobuf:"varint,7,opt,name=friends_count" json:"friends_count,omitempty"`
	ProfileBackgroundColor    *string `protobuf:"bytes,8,opt,name=profile_background_color" json:"profile_background_color,omitempty"`
	FavouritesCount           *int32  `protobuf:"varint,9,opt,name=favourites_count" json:"favourites_count,omitempty"`
	Description               *string `protobuf:"bytes,10,opt,name=description" json:"description,omitempty"`
	Notifications             *string `protobuf:"bytes,11,opt,name=notifications" json:"notifications,omitempty"`
	ProfileTextColor          *string `protobuf:"bytes,12,opt,name=profile_text_color" json:"profile_text_color,omitempty"`
	Url                       *string `protobuf:"bytes,13,opt,name=url" json:"url,omitempty"`
	TimeZone                  *string `protobuf:"bytes,14,opt,name=time_zone" json:"time_zone,omitempty"`
	StatusesCount             *int32  `protobuf:"varint,15,opt,name=statuses_count" json:"statuses_count,omitempty"`
	ProfileLinkColor          *string `protobuf:"bytes,16,opt,name=profile_link_color" json:"profile_link_color,omitempty"`
	GeoEnabled                *bool   `protobuf:"varint,17,opt,name=geo_enabled" json:"geo_enabled,omitempty"`
	ProfileBackgroundImageUrl *string `protobuf:"bytes,18,opt,name=profile_background_image_url" json:"profile_background_image_url,omitempty"`
	Protected                 *bool   `protobuf:"varint,19,opt,name=protected" json:"protected,omitempty"`
	ContributorsEnabled       *bool   `protobuf:"varint,20,opt,name=contributors_enabled" json:"contributors_enabled,omitempty"`
	ProfileSidebarFillColor   *string `protobuf:"bytes,21,opt,name=profile_sidebar_fill_color" json:"profile_sidebar_fill_color,omitempty"`
	Name                      *string `protobuf:"bytes,22,opt,name=name" json:"name,omitempty"`
	ProfileBackgroundTile     *string `protobuf:"bytes,23,opt,name=profile_background_tile" json:"profile_background_tile,omitempty"`
	CreatedAt                 *string `protobuf:"bytes,24,opt,name=created_at" json:"created_at,omitempty"`
	ProfileImageUrl           *string `protobuf:"bytes,25,opt,name=profile_image_url" json:"profile_image_url,omitempty"`
	Id                        *int64  `protobuf:"varint,26,opt,name=id" json:"id,omitempty"`
	UtcOffset                 *int32  `protobuf:"varint,27,opt,name=utc_offset" json:"utc_offset,omitempty"`
	ProfileSidebarBorderColor *string `protobuf:"bytes,28,opt,name=profile_sidebar_border_color" json:"profile_sidebar_border_color,omitempty"`
	XXX_unrecognized          []byte  `json:"-"`
}

func (this *User) Reset()         { *this = User{} }
func (this *User) String() string { return proto.CompactTextString(this) }
func (*User) ProtoMessage()       {}

func (this *User) GetLang() string {
	if this != nil && this.Lang != nil {
		return *this.Lang
	}
	return ""
}

func (this *User) GetVerified() bool {
	if this != nil && this.Verified != nil {
		return *this.Verified
	}
	return false
}

func (this *User) GetFollowersCount() int32 {
	if this != nil && this.FollowersCount != nil {
		return *this.FollowersCount
	}
	return 0
}

func (this *User) GetLocation() string {
	if this != nil && this.Location != nil {
		return *this.Location
	}
	return ""
}

func (this *User) GetScreenName() string {
	if this != nil && this.ScreenName != nil {
		return *this.ScreenName
	}
	return ""
}

func (this *User) GetFollowing() bool {
	if this != nil && this.Following != nil {
		return *this.Following
	}
	return false
}

func (this *User) GetFriendsCount() int32 {
	if this != nil && this.FriendsCount != nil {
		return *this.FriendsCount
	}
	return 0
}

func (this *User) GetProfileBackgroundColor() string {
	if this != nil && this.ProfileBackgroundColor != nil {
		return *this.ProfileBackgroundColor
	}
	return ""
}

func (this *User) GetFavouritesCount() int32 {
	if this != nil && this.FavouritesCount != nil {
		return *this.FavouritesCount
	}
	return 0
}

func (this *User) GetDescription() string {
	if this != nil && this.Description != nil {
		return *this.Description
	}
	return ""
}

func (this *User) GetNotifications() string {
	if this != nil && this.Notifications != nil {
		return *this.Notifications
	}
	return ""
}

func (this *User) GetProfileTextColor() string {
	if this != nil && this.ProfileTextColor != nil {
		return *this.ProfileTextColor
	}
	return ""
}

func (this *User) GetUrl() string {
	if this != nil && this.Url != nil {
		return *this.Url
	}
	return ""
}

func (this *User) GetTimeZone() string {
	if this != nil && this.TimeZone != nil {
		return *this.TimeZone
	}
	return ""
}

func (this *User) GetStatusesCount() int32 {
	if this != nil && this.StatusesCount != nil {
		return *this.StatusesCount
	}
	return 0
}

func (this *User) GetProfileLinkColor() string {
	if this != nil && this.ProfileLinkColor != nil {
		return *this.ProfileLinkColor
	}
	return ""
}

func (this *User) GetGeoEnabled() bool {
	if this != nil && this.GeoEnabled != nil {
		return *this.GeoEnabled
	}
	return false
}

func (this *User) GetProfileBackgroundImageUrl() string {
	if this != nil && this.ProfileBackgroundImageUrl != nil {
		return *this.ProfileBackgroundImageUrl
	}
	return ""
}

func (this *User) GetProtected() bool {
	if this != nil && this.Protected != nil {
		return *this.Protected
	}
	return false
}

func (this *User) GetContributorsEnabled() bool {
	if this != nil && this.ContributorsEnabled != nil {
		return *this.ContributorsEnabled
	}
	return false
}

func (this *User) GetProfileSidebarFillColor() string {
	if this != nil && this.ProfileSidebarFillColor != nil {
		return *this.ProfileSidebarFillColor
	}
	return ""
}

func (this *User) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *User) GetProfileBackgroundTile() string {
	if this != nil && this.ProfileBackgroundTile != nil {
		return *this.ProfileBackgroundTile
	}
	return ""
}

func (this *User) GetCreatedAt() string {
	if this != nil && this.CreatedAt != nil {
		return *this.CreatedAt
	}
	return ""
}

func (this *User) GetProfileImageUrl() string {
	if this != nil && this.ProfileImageUrl != nil {
		return *this.ProfileImageUrl
	}
	return ""
}

func (this *User) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *User) GetUtcOffset() int32 {
	if this != nil && this.UtcOffset != nil {
		return *this.UtcOffset
	}
	return 0
}

func (this *User) GetProfileSidebarBorderColor() string {
	if this != nil && this.ProfileSidebarBorderColor != nil {
		return *this.ProfileSidebarBorderColor
	}
	return ""
}

func init() {
}
